### ISSUE TITLE
Historik i vejledningsdokumentet

### ISSUE THREAD

**Issue by recks** [AndersKlinting/divisionsmatchberegning#7]
Historik-kapitlet i Divisionsmatchberegning.pdf fylder 4½ side, hvilket virker lidt voldsomt i starten af dokumentet. Den har dertil sjældent relevans for læseren.
Overvej at flytte den bagest, evt. til et bilag. Den

**Comment by AndersKlinting** [comment]
Beklager det sene svar - men et lyder helt rimeligt og kommer med i næste version
